In [81]:
import numpy as np 

In [82]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [83]:
arr[6]

np.int64(17)

In [84]:
arrs = arr[2:5]

In [85]:
print(arrs)

[13 14 15]


## slicing of matrix


In [86]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [87]:
s = arr[5][4]
print(s)

30


In [88]:
s = arr[0:2,1:3]
s

array([[2, 3],
       [7, 8]])

In [89]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [90]:
s = arr[3:6,3:6]
s

array([[19, 20],
       [24, 25],
       [29, 30]])

In [91]:
s = arr[:,2]
s

array([ 3,  8, 13, 18, 23, 28])

In [92]:
arr1 = np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
boll = arr1 % 2 == 0
boll

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [94]:
arr1[boll]

array([ 2,  4,  6,  8, 10])

# array operation

### arithmentic operations